import { Printer } from "lucide-react";
import { Button } from "@/components/ui/button";
import {
  Card,
  CardContent,
  CardDescription,
  CardHeader,
  CardTitle,
} from "@/components/ui/card";
import {
  Table,
  TableBody,
  TableCell,
  TableFooter,
  TableHead,
  TableHeader,
  TableRow,
} from "@/components/ui/table";

const numberFormatter = new Intl.NumberFormat("en-LK");
const currencyFormatter = new Intl.NumberFormat("en-LK", {
  style: "currency",
  currency: "LKR",
  maximumFractionDigits: 2,
});

export default function DashboardReports({ analytics, user }) {
  const dayTypeRows = [
    { id: "weekday", label: "Weekdays", value: analytics.dayType.weekday },
    { id: "weekend", label: "Weekends", value: analytics.dayType.weekend },
  ];
  const timeOfDayRows = [
    { id: "morning", label: "Morning", value: analytics.timeOfDay.morning },
    { id: "evening", label: "Evening", value: analytics.timeOfDay.evening },
  ];
  const generatedAt = new Date().toLocaleString("en-LK", {
    dateStyle: "long",
    timeStyle: "short",
  });

  return (
    <section className="dashboard-report mt-8 space-y-6">
      <div className="dashboard-report-actions flex flex-wrap items-center justify-between gap-4">
        <div>
          <h2 className="text-2xl font-bold text-slate-900">Reports</h2>
          <p className="mt-1 text-sm text-slate-500">
            Exact values corresponding to the dashboard charts.
          </p>
        </div>
        <Button type="button" onClick={() => window.print()}>
          <Printer className="mr-2 h-4 w-4" />
          Print Report
        </Button>
      </div>

      <header className="hidden border-b-2 border-slate-900 pb-4 print:block">
        <h1 className="text-2xl font-bold">Hospital Management System</h1>
        <p className="mt-1 text-lg font-semibold">Dashboard Analytics Report</p>
        <div className="mt-3 grid grid-cols-2 gap-2 text-sm">
          <p>Generated: {generatedAt}</p>
          <p>
            Generated by: {[user?.firstName, user?.lastName].filter(Boolean).join(" ") || "Administrator"}
          </p>
          <p className="col-span-2">
            Scope: All appointments except rejected and cancelled appointments
          </p>
        </div>
      </header>

      <div className="grid gap-6 xl:grid-cols-2 print:block">
        <MetricReportTable
          title="Patient Visits by Doctor"
          description="Active appointments assigned to each doctor."
          rows={analytics.visitsByDoctor}
          valueHeading="Visits"
        />
        <RevenueReportTable rows={analytics.revenueByDoctor} />
        <MetricReportTable
          title="Weekday vs Weekend Visits"
          description="Appointment demand based on the scheduled day."
          rows={dayTypeRows}
          valueHeading="Visits"
        />
        <MetricReportTable
          title="Morning vs Evening Visits"
          description="Morning is before 12:00; evening begins at 12:00."
          rows={timeOfDayRows}
          valueHeading="Visits"
        />
      </div>
    </section>
  );
}

function MetricReportTable({ title, description, rows, valueHeading }) {
  const total = rows.reduce((sum, row) => sum + row.value, 0);

  return (
    <ReportCard title={title} description={description}>
      {!rows.length || total === 0 ? (
        <EmptyReport />
      ) : (
        <Table>
          <TableHeader>
            <TableRow>
              <TableHead>Category</TableHead>
              <TableHead className="text-right">{valueHeading}</TableHead>
              <TableHead className="text-right">Percentage</TableHead>
            </TableRow>
          </TableHeader>
          <TableBody>
            {rows.map((row) => (
              <TableRow key={row.id}>
                <TableCell className="font-medium">{row.label}</TableCell>
                <TableCell className="text-right">
                  {numberFormatter.format(row.value)}
                </TableCell>
                <TableCell className="text-right">
                  {formatPercentage(row.value, total)}
                </TableCell>
              </TableRow>
            ))}
          </TableBody>
          <TableFooter>
            <TableRow>
              <TableCell>Total</TableCell>
              <TableCell className="text-right">
                {numberFormatter.format(total)}
              </TableCell>
              <TableCell className="text-right">100%</TableCell>
            </TableRow>
          </TableFooter>
        </Table>
      )}
    </ReportCard>
  );
}

function RevenueReportTable({ rows }) {
  const totalRevenue = rows.reduce((sum, row) => sum + row.value, 0);
  const totalAppointments = rows.reduce(
    (sum, row) => sum + (row.appointmentCount ?? 0),
    0,
  );

  return (
    <ReportCard
      title="Revenue by Doctor"
      description="Consultation revenue from paid and diagnosed appointments."
    >
      {!rows.length ? (
        <EmptyReport />
      ) : (
        <Table>
          <TableHeader>
            <TableRow>
              <TableHead>Doctor</TableHead>
              <TableHead className="text-right">Appointments</TableHead>
              <TableHead className="text-right">Revenue</TableHead>
              <TableHead className="text-right">Share</TableHead>
            </TableRow>
          </TableHeader>
          <TableBody>
            {rows.map((row) => (
              <TableRow key={row.id}>
                <TableCell className="font-medium">{row.label}</TableCell>
                <TableCell className="text-right">
                  {numberFormatter.format(row.appointmentCount ?? 0)}
                </TableCell>
                <TableCell className="text-right">
                  {currencyFormatter.format(row.value)}
                </TableCell>
                <TableCell className="text-right">
                  {formatPercentage(row.value, totalRevenue)}
                </TableCell>
              </TableRow>
            ))}
          </TableBody>
          <TableFooter>
            <TableRow>
              <TableCell>Total</TableCell>
              <TableCell className="text-right">
                {numberFormatter.format(totalAppointments)}
              </TableCell>
              <TableCell className="text-right">
                {currencyFormatter.format(totalRevenue)}
              </TableCell>
              <TableCell className="text-right">
                {totalRevenue ? "100%" : "0%"}
              </TableCell>
            </TableRow>
          </TableFooter>
        </Table>
      )}
    </ReportCard>
  );
}

function ReportCard({ title, description, children }) {
  return (
    <Card className="report-card border-slate-200 print:mb-6 print:break-inside-avoid print:shadow-none">
      <CardHeader>
        <CardTitle>{title}</CardTitle>
        <CardDescription>{description}</CardDescription>
      </CardHeader>
      <CardContent>{children}</CardContent>
    </Card>
  );
}

function EmptyReport() {
  return (
    <p className="py-8 text-center text-sm text-slate-500">
      No data is available for this report.
    </p>
  );
}

function formatPercentage(value, total) {
  if (!total) return "0%";
  return `${Math.round((value / total) * 100)}%`;
}
